language: generic
dist: trusty

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended texlive-xetex texlive-full

script:
  - xelatex cv.tex

deploy:
  provider: script
  script: bash publish.sh
  skip_cleanup: true
  on:
    branch: master
